---
title: "AirBNB Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(p8105.datasets)
```

```{r include=FALSE}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2, text_label=str_c("Price: ",price)) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb %>%
  mutate(text_label=str_c("Price: ",price)) %>% 
  plot_ly(
    x=~lat,y=~long,color=~price,
    type="scatter",
    mode="markers",
    alpha = .5,
    text=~text_label
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>% 
  plot_ly(
    y=~price,color=~neighbourhood,
    type="box"
  )
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood=fct_reorder(neighbourhood,n)) %>% 
  plot_ly(
    x=~neighbourhood,y=~n,type="bar"
  )
```

