---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

We are going to make some plotly plots

## load pacakges and data

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

let's get some data.

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2, text_label=str_c("Price: ",price)) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

```{r}
nyc_airbnb %>%
  mutate(text_label=str_c("Price: ",price)) %>% 
  plot_ly(
    x=~lat,y=~long,color=~price,
    type="scatter",
    mode="markers",
    alpha = .5,
    text=~text_label
  )
```

## boxplot
```{r}
nyc_airbnb %>% 
  plot_ly(
    y=~price,color=~neighbourhood,
    type="box"
  )
```

## bar plot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood=fct_reorder(neighbourhood,n)) %>% 
  plot_ly(
    x=~neighbourhood,y=~n,type="bar"
  )
```

## ggplotly ...

```{r}
box_ggplot = 
  nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```



